/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package enterprise.jotto.entities;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlTransient;

/**
 * <p>This entity provides a very basic representation of a web application
 * user.</p>
 *
 * <p>This code was generated by NetBeans 5.5 DEV.</p>
 *
 * @author rlubke
 */
@Entity
@Table(name = "JUSER")
@NamedQueries( {
    @NamedQuery(name = "Juser.findById", query = "SELECT j FROM Juser j WHERE j.id = :id"), 
    @NamedQuery(name = "Juser.findByFirstname", query = "SELECT j FROM Juser j WHERE j.firstname = :firstname"), 
    @NamedQuery(name = "Juser.findByLastname", query = "SELECT j FROM Juser j WHERE j.lastname = :lastname"), 
    @NamedQuery(name = "Juser.findByUsername", query = "SELECT j FROM Juser j WHERE j.username = :username"), 
    @NamedQuery(name = "Juser.findByPassword", query = "SELECT j FROM Juser j WHERE j.password = :password"), 
    @NamedQuery(name = "Juser.findBySince", query = "SELECT j FROM Juser j WHERE j.since = :since")})
public class Juser implements Serializable {
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "juserid")
    private Collection<Jstats> jstatsCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "juserid")
    private Collection<Jgame> jgameCollection;

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name = "ID", nullable = false)
    private Integer id;

    @Column(name = "FIRSTNAME", nullable = false)
    private String firstname;

    @Column(name = "LASTNAME", nullable = false)
    private String lastname;

    @Column(name = "USERNAME", nullable = false)
    private String username;

    @Column(name = "PASSWORD", nullable = false)
    private String password;

    @Column(name = "SINCE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date since;
    
    /** Creates a new instance of Juser */
    public Juser() {
    }

    public Juser(Integer id) {
        this.id = id;
    }

    public Juser(Integer id, String firstname, String lastname, String username, String password) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.username = username;
        this.password = password;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getSince() {
        return this.since;
    }

    public void setSince(Date since) {
        this.since = since;
    }

    public int hashCode() {
        int hash = 0;
        hash += (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    public boolean equals(Object object) {
        if (object == null || !this.getClass().equals(object.getClass())) {
            return false;
        }
        Juser other = (Juser)object;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) return false;
        return true;
    }

    public String toString() {
        //TODO change toString() implementation to return a better display name
        return "" + this.id;
    }

    @XmlTransient
    public Collection<Jgame> getJgameCollection() {
        return jgameCollection;
    }

    public void setJgameCollection(Collection<Jgame> jgameCollection) {
        this.jgameCollection = jgameCollection;
    }

    @XmlTransient
    public Collection<Jstats> getJstatsCollection() {
        return jstatsCollection;
    }

    public void setJstatsCollection(Collection<Jstats> jstatsCollection) {
        this.jstatsCollection = jstatsCollection;
    }
    
}
